import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding Indonesian UMKM templates...");

  // Indonesian UMKM Templates - Phase 12.4 Seeding
  const indonesianTemplates = [
    // ============================================
    // TEMPLATE 1: Showcase Produk UMKM - 30 Detik
    // ============================================
    {
      name: "Showcase Produk UMKM - 30 Detik",
      slug: "umkm-produk-showcase-30s",
      description:
        "Template showcase produk UMKM klasik 30 detik untuk Instagram Reels/TikTok. Cocok untuk makanan, fashion, skincare, dan aksesoris. Struktur: Hook (3s) → Product Demo (12s) → Benefit (10s) → CTA (5s).",
      category: "UMKM",
      tags: ["produk", "showcase", "reels", "tiktok", "30s", "indonesia"],
      industry: "E-commerce",
      format: "REELS",
      style: "Commercial",
      totalDuration: 30,
      aspectRatio: "9:16",
      shotCount: 5,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "Poppins", "Montserrat"],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 30,
          },
          {
            key: "price",
            label: "Harga",
            required: false,
            defaultValue: "Mulai Rp 49.000",
          },
          { key: "promo", label: "Kode Promo", required: false },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Beli Sekarang",
          },
        ],
      },
      creditsCost: 5,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Hook visual - close up produk dengan lighting dramatis",
          prompt:
            "Ultra close-up premium product shot, dramatic rim lighting, shallow depth of field, cinematic color grading, 4k, commercial photography style",
          negativePrompt:
            "blur, low quality, watermark, text, logo, oversaturated, distorted",
          camera: "Macro 100mm",
          lighting: "Dramatic rim light, dark background",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 10001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 1,
          timeRange: "3-15s",
          duration: 12,
          description: "Product demo - penggunaan real dengan slow motion",
          prompt:
            "Product in use demonstration, slow motion 60fps, person using product naturally, Indonesian home setting, authentic lifestyle, smooth camera movement",
          negativePrompt:
            "staged, fake, oversaturated, artificial, studio lighting, posed",
          camera: "Handheld 35mm, smooth gimbal",
          lighting: "Natural window light, warm tones",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "handheld",
          motionStrength: 0.4,
          seed: 10002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: { logo: { position: "bottom-right" } },
        },
        {
          index: 2,
          timeRange: "15-25s",
          duration: 10,
          description: "Benefit highlights - text overlay fitur utama",
          prompt:
            "Clean benefit showcase, split screen or sequential shots, key features highlighted, minimal text space, Indonesian context, bright and airy",
          negativePrompt: "cluttered, dark, confusing, too much text, messy",
          camera: "Static medium, 50mm",
          lighting: "Bright even lighting, high key",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 10003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{feature_1}\n{feature_2}\n{feature_3}",
              position: "bottom-center",
              fontSize: 28,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 3,
          timeRange: "25-28s",
          duration: 3,
          description: "Social proof - rating/testimoni singkat",
          prompt:
            "Quick testimonial flash, 5-star rating animation, happy customer face, authentic Indonesian review, genuine expression",
          negativePrompt:
            "fake, acted, scripted, overly polished, stock photo feel",
          camera: "Selfie style, eye level",
          lighting: "Ring light or natural",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 10004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "⭐⭐⭐⭐⭐ {rating}/5",
              position: "center",
              fontSize: 36,
              color: "#FFD700",
            },
          },
        },
        {
          index: 4,
          timeRange: "28-30s",
          duration: 2,
          description: "CTA akhir - logo, harga, kode promo, swipe up",
          prompt:
            "Clean end card, product packshot, logo animation, price display, promo code, CTA button visual, Indonesian brand colors",
          negativePrompt: "cluttered, cheap, low quality, confusing layout",
          camera: "Static centered",
          lighting: "Even studio lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 10005,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-center", scale: 1.2 },
            text: {
              content: "{product_name}\n{price}\nKode: {promo}\n{cta}",
              position: "center",
              fontSize: 32,
              color: "#FFFFFF",
              backgroundColor: "#1A1A2E",
              padding: 20,
              borderRadius: 16,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 2: Problem-Solution Story - 20 Detik
    // ============================================
    {
      name: "Problem-Solution Story - 20 Detik",
      slug: "umkm-problem-solution-20s",
      description:
        "Format storytelling problem-solution 20 detik. Cocok untuk produk yang memecahkan masalah spesifik (skincare, household, productivity). Struktur: Problem (3s) → Solution (4s) → Demo (6s) → Result (4s) → CTA (3s).",
      category: "UMKM",
      tags: [
        "storytelling",
        "problem-solution",
        "skincare",
        "household",
        "20s",
      ],
      industry: "E-commerce",
      format: "REELS",
      style: "Storytelling",
      totalDuration: 20,
      aspectRatio: "9:16",
      shotCount: 5,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["top-right", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "DM Sans", "Space Grotesk", "JetBrains Mono"],
        },
        jingle: { required: false },
        textPlaceholders: [
          { key: "problem", label: "Masalah", required: true, maxLength: 35 },
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 25,
          },
          { key: "feature_1", label: "Fitur 1", required: true, maxLength: 30 },
          { key: "feature_2", label: "Fitur 2", required: true, maxLength: 30 },
          {
            key: "feature_3",
            label: "Fitur 3",
            required: false,
            maxLength: 30,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Cek Produk",
          },
        ],
      },
      creditsCost: 4,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Problem - relatable pain point",
          prompt:
            "Clean modern problem visualization, person struggling with {problem}, minimal setup, muted colors for problem state, relatable Indonesian home/office, slight frustration",
          negativePrompt: "dramatic, messy, chaotic, overacted, dark",
          camera: "Static wide, 35mm",
          lighting: "Cool flat lighting, problem mood",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 100001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{problem}? 🤔",
              position: "center",
              fontSize: 36,
              color: "#EF4444",
              fontWeight: "medium",
              backgroundColor: "#FEF2F2",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-7s",
          duration: 4,
          description: "Solution reveal - product entrance",
          prompt:
            "Clean product reveal, {product_name} entering frame elegantly, lighting shifts to warm/bright, hopeful transition, product hero moment",
          negativePrompt: "chaotic, dark, messy transition, cheap",
          camera: "Medium, 50mm",
          lighting: "Bright transition to warm key light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-zoom-in",
          motionStrength: 0.3,
          seed: 100002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-right" },
            text: {
              content: "Solusi: {product_name}",
              position: "bottom-center",
              fontSize: 32,
              color: "#22C55E",
            },
          },
        },
        {
          index: 2,
          timeRange: "7-13s",
          duration: 6,
          description: "Demo cepat - 3 fitur utama",
          prompt:
            "Quick feature montage, 3 distinct benefits shown rapidly, split screen or fast cuts, {feature_1}, {feature_2}, {feature_3}, clean UI overlays, Indonesian hands demonstrating",
          negativePrompt:
            "slow, boring, confusing, too many features, cluttered",
          camera: "Fast cuts, various angles",
          lighting: "Bright commercial",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "fast-cut",
          motionStrength: 0.7,
          seed: 100003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "✨ {feature_1}\n✨ {feature_2}\n✨ {feature_3}",
              position: "bottom-center",
              fontSize: 24,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 6,
            },
          },
        },
        {
          index: 3,
          timeRange: "13-17s",
          duration: 4,
          description: "Result - happy user, problem solved",
          prompt:
            "Satisfied user, problem completely solved, genuine smile, relaxed posture, warm lighting, Indonesian context, authentic relief expression",
          negativePrompt: "fake smile, forced, overly dramatic, studio",
          camera: "Medium close-up, 85mm",
          lighting: "Warm golden hour, natural",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 100004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Masalah terpecahkan! ✅",
              position: "center",
              fontSize: 36,
              color: "#22C55E",
              fontWeight: "bold",
            },
          },
        },
        {
          index: 4,
          timeRange: "17-20s",
          duration: 3,
          description: "CTA - brand + action",
          prompt:
            "Clean brand end frame, logo, product, CTA button, website/social, consistent brand colors, professional finish",
          negativePrompt: "amateur, cluttered, low quality",
          camera: "Static centered",
          lighting: "Brand color gradient",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 100005,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "center" },
            text: {
              content: "{cta}",
              position: "bottom-center",
              fontSize: 40,
              color: "#FFFFFF",
              backgroundColor: "#1A1A2E",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 3: How-To/Tutorial - 60 Detik
    // ============================================
    {
      name: "How-To/Tutorial - 60 Detik",
      slug: "umkm-howto-tutorial-60s",
      description:
        "Format tutorial/educational 60 detik untuk produk yang butuh demonstrasi (masak, DIY, skincare routine, tech setup). Struktur: Hook (5s) → Intro Produk (10s) → Step 1 (10s) → Step 2 (10s) → Step 3 (10s) → Result (10s) → CTA (5s).",
      category: "UMKM",
      tags: [
        "tutorial",
        "how-to",
        "educational",
        "skincare",
        "cooking",
        "diy",
        "60s",
      ],
      industry: "E-commerce",
      format: "REELS",
      style: "Educational",
      totalDuration: 60,
      aspectRatio: "9:16",
      shotCount: 7,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["top-left"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "DM Sans", "Space Grotesk"],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 25,
          },
          { key: "step_1", label: "Langkah 1", required: true, maxLength: 30 },
          { key: "step_2", label: "Langkah 2", required: true, maxLength: 30 },
          { key: "step_3", label: "Langkah 3", required: true, maxLength: 30 },
          {
            key: "result",
            label: "Hasil Akhir",
            required: true,
            maxLength: 35,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Coba Sekarang",
          },
          { key: "website", label: "Website/IG", required: false },
        ],
      },
      creditsCost: 7,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-5s",
          duration: 5,
          description: "Problem hook - relatable pain point",
          prompt:
            "Relatable problem scenario, Indonesian person looking frustrated/confused, authentic expression, cinematic lighting",
          camera: "Close-up, 85mm",
          lighting: "Dramatic side lighting for mood",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 20001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{problem}",
              position: "center",
              fontSize: 48,
              color: "#FFFFFF",
              backgroundColor: "#E53E3E",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
        {
          index: 1,
          timeRange: "5-15s",
          duration: 10,
          description: "Introduksi produk sebagai solusi",
          prompt:
            "Product reveal as solution, clean transition from problem, bright lighting, hopeful mood, product hero shot",
          camera: "Medium, 50mm",
          lighting: "Bright even lighting, high key",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-zoom-in",
          motionStrength: 0.3,
          seed: 20002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-right" },
            text: {
              content: "Solusi: {product_name}",
              position: "bottom-center",
              fontSize: 40,
              color: "#2F855A",
            },
          },
        },
        {
          index: 2,
          timeRange: "15-25s",
          duration: 10,
          description: "Step 1 - demonstrasi jelas",
          prompt:
            "Clear step-by-step demonstration, hands showing action, top-down or 45° angle, instructional style, slow pace",
          camera: "Top-down 45°, 35mm",
          lighting: "Bright shadowless lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.2,
          seed: 20003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "1️⃣ {step_1}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#2B6CB0",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 3,
          timeRange: "25-35s",
          duration: 10,
          description: "Step 2 - detail teknik",
          prompt:
            "Close up technique detail, precise movements, educational focus, clear visibility of method",
          camera: "Macro close-up, 100mm",
          lighting: "Focused task lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 20004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "2️⃣ {step_2}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#2B6CB0",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 4,
          timeRange: "35-45s",
          duration: 10,
          description: "Step 3 - finishing touch",
          prompt:
            "Final step completion, satisfying result reveal, clean finished state, sense of accomplishment",
          camera: "Medium wide, 35mm",
          lighting: "Natural bright lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-pan",
          motionStrength: 0.2,
          seed: 20005,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "3️⃣ {step_3}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#2B6CB0",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 5,
          timeRange: "45-55s",
          duration: 10,
          description: "Result reveal - before/after atau hasil akhir",
          prompt:
            "Dramatic result reveal, before/after split or transformation, glowing satisfied user, product in use successfully",
          camera: "Split screen or transition, 50mm",
          lighting: "Bright confident lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 20006,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "✨ {result}",
              position: "center",
              fontSize: 52,
              color: "#2F855A",
              fontWeight: "bold",
            },
          },
        },
        {
          index: 6,
          timeRange: "55-60s",
          duration: 5,
          description: "CTA dengan brand reinforcement",
          prompt:
            "Clean end frame with product, logo, CTA button, website/social handle, consistent brand colors",
          camera: "Static centered",
          lighting: "Even studio lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 20007,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "center", scale: 1.5 },
            text: {
              content: "{cta}\n{website}",
              position: "bottom-center",
              fontSize: 42,
              color: "#FFFFFF",
              backgroundColor: "#1A202C",
              padding: 20,
              borderRadius: 12,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 4: Flash Sale/Promo - 15 Detik
    // ============================================
    {
      name: "Flash Sale/Promo - 15 Detik",
      slug: "umkm-flash-sale-15s",
      description:
        "Format flash sale 15 detik high energy untuk promo terbatas, discount besar, event khusus. Struktur: Discount Hook (3s) → Product Grid (5s) → Timer + Code (4s) → CTA (3s).",
      category: "UMKM",
      tags: ["flash-sale", "promo", "discount", "urgency", "15s", "fomo"],
      industry: "E-commerce",
      format: "REELS",
      style: "High Energy",
      totalDuration: 15,
      aspectRatio: "9:16",
      shotCount: 4,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["top-left", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "Poppins", "Montserrat", "Bebas Neue"],
        },
        jingle: {
          required: true,
          suggestions: ["Upbeat jingle", "SFX whoosh", "Countdown tick"],
        },
        textPlaceholders: [
          {
            key: "discount",
            label: "Diskon (contoh: 50%)",
            required: true,
            maxLength: 10,
          },
          {
            key: "deadline",
            label: "Batas Waktu (contoh: Hingga Malam Ini)",
            required: true,
            maxLength: 30,
          },
          {
            key: "promo_code",
            label: "Kode Promo",
            required: true,
            maxLength: 15,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Beli Sekarang",
          },
        ],
      },
      creditsCost: 4,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Hook - big discount number animasi",
          prompt:
            "Huge animated discount number '50%' bursting onto screen, energetic particles, Indonesian festival vibe, bold typography",
          camera: "Static, centered",
          lighting: "High contrast, vibrant colors",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.8,
          seed: 30001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{discount} OFF!",
              position: "center",
              fontSize: 96,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#E53E3E",
              padding: 24,
              borderRadius: 16,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-8s",
          duration: 5,
          description: "Product grid cepat - 3-4 produk bestseller",
          prompt:
            "Fast-paced product grid montage, 3-4 bestseller products quick cuts, smooth transitions, Indonesian UMKM products variety",
          camera: "Quick cuts, various angles",
          lighting: "Bright commercial lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "fast-cut",
          motionStrength: 0.9,
          seed: 30002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: { logo: { position: "top-left" } },
        },
        {
          index: 2,
          timeRange: "8-12s",
          duration: 4,
          description: "Timer countdown + kode promo",
          prompt:
            "Animated countdown timer ticking down, promo code prominently displayed, urgency visual cues, FOMO atmosphere",
          camera: "Static",
          lighting: "High contrast red/black theme",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.3,
          seed: 30003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "⏰ {deadline}\n🔥 KODE: {promo_code}",
              position: "center",
              fontSize: 40,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#C53030",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
        {
          index: 3,
          timeRange: "12-15s",
          duration: 3,
          description: "CTA final - swipe up/link bio",
          prompt:
            "Strong final CTA, swipe up animation or link in bio pointer, brand logo, urgent but friendly tone",
          camera: "Static",
          lighting: "Brand colors theme",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.2,
          seed: 30004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-left" },
            text: {
              content: "{cta} 👆\nLink di Bio",
              position: "bottom-center",
              fontSize: 48,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#2D3748",
              padding: 20,
              borderRadius: 12,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 5: Brand Story/Founder - 90 Detik
    // ============================================
    {
      name: "Brand Story/Founder - 90 Detik",
      slug: "umkm-brand-story-90s",
      description:
        "Format brand story 90 detik untuk menceritakan journey founder, nilai-nilai brand, dan koneksi emosional. Cocok untuk brand awareness, about us page, investor pitch. Struktur: Origin (10s) → Founder (10s) → Flashback (10s) → Process (12s) → Sourcing (10s) → Team (10s) → Customers (13s) → Vision (10s) → End Card (5s).",
      category: "UMKM",
      tags: [
        "brand-story",
        "founder",
        "documentary",
        "heritage",
        "90s",
        "emotional",
      ],
      industry: "E-commerce",
      format: "REELS",
      style: "Documentary",
      totalDuration: 90,
      aspectRatio: "9:16",
      shotCount: 9,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["center", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 4 },
        font: {
          required: true,
          suggestions: [
            "Inter",
            "DM Sans",
            "Space Grotesk",
            "Playfair Display",
          ],
        },
        jingle: {
          required: true,
          suggestions: [
            "Ambient brand track",
            "Traditional Indonesian instrument",
            "Heartwarming melody",
          ],
        },
        textPlaceholders: [
          {
            key: "founder_name",
            label: "Nama Pendiri",
            required: true,
            maxLength: 30,
          },
          {
            key: "brand_name",
            label: "Nama Brand",
            required: true,
            maxLength: 25,
          },
          {
            key: "year_founded",
            label: "Tahun Berdiri",
            required: true,
            maxLength: 4,
          },
          {
            key: "mission",
            label: "Misi Brand",
            required: true,
            maxLength: 50,
          },
          { key: "tagline", label: "Tagline", required: true, maxLength: 40 },
          { key: "website", label: "Website", required: false },
          { key: "instagram", label: "Instagram Handle", required: false },
        ],
      },
      creditsCost: 9,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-10s",
          duration: 10,
          description: "Opening - landscape Indonesia / workshop",
          prompt:
            "Cinematic wide shot of Indonesian landscape or artisanal workshop, golden hour, establishing shot, sense of place and origin",
          camera: "Drone wide or 24mm wide",
          lighting: "Golden hour natural light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-drone-pan",
          motionStrength: 0.3,
          seed: 40001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 1,
          timeRange: "10-20s",
          duration: 10,
          description: "Pendiri - potret & wawancara visual",
          prompt:
            "Portrait of founder working passionately, authentic candid moments, hands crafting, eyes focused, Indonesian entrepreneur pride",
          camera: "Medium close-up, 85mm",
          lighting: "Natural window light, Rembrandt style",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 40002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{founder_name}\nPendiri {brand_name}",
              position: "lower-third",
              fontSize: 32,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 4,
            },
          },
        },
        {
          index: 2,
          timeRange: "20-30s",
          duration: 10,
          description: "Flashback/awal mula - foto lama style",
          prompt:
            "Vintage film look, old photos coming to life, humble beginnings, small kitchen/garage startup, nostalgic warm tones",
          camera: "Vintage 16mm film aesthetic",
          lighting: "Warm tungsten, film grain",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-zoom",
          motionStrength: 0.2,
          seed: 40003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Sejak {year_founded}",
              position: "center",
              fontSize: 48,
              color: "#F6E05E",
              fontWeight: "light",
            },
          },
        },
        {
          index: 3,
          timeRange: "30-42s",
          duration: 12,
          description: "Proses produksi - craftsmanship detail",
          prompt:
            "Detailed craftsmanship process, hands making product, traditional techniques, quality focus, slow motion details, pride in work",
          camera: "Macro + medium, 50-100mm",
          lighting: "Directional craft lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-dolly",
          motionStrength: 0.2,
          seed: 40004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 4,
          timeRange: "42-52s",
          duration: 10,
          description: "Bahan baku lokal / sourcing",
          prompt:
            "Local ingredients sourcing, Indonesian farmers/suppliers, fresh natural materials, community connection, sustainable",
          camera: "Documentary handheld",
          lighting: "Natural outdoor light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "handheld",
          motionStrength: 0.3,
          seed: 40005,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "100% Bahan Lokal Indonesia",
              position: "lower-third",
              fontSize: 28,
              color: "#2F855A",
              backgroundColor: "#F0FFF4",
              padding: 8,
              borderRadius: 4,
            },
          },
        },
        {
          index: 5,
          timeRange: "52-62s",
          duration: 10,
          description: "Tim & komunitas - togetherness",
          prompt:
            "Team working together, laughter, collaboration, Indonesian workplace culture, gotong royong spirit, diverse ages",
          camera: "Wide group shot, 35mm",
          lighting: "Warm inclusive lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-pan",
          motionStrength: 0.2,
          seed: 40006,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Tim yang Penuh Semangat",
              position: "lower-third",
              fontSize: 28,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 4,
            },
          },
        },
        {
          index: 6,
          timeRange: "62-75s",
          duration: 13,
          description: "Pelanggan senik / testimoni visual",
          prompt:
            "Happy customers using product, genuine smiles, diverse Indonesian faces, lifestyle moments, trust and satisfaction",
          camera: "Candid lifestyle, 35-50mm",
          lighting: "Natural lifestyle lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 40007,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{mission}",
              position: "center",
              fontSize: 36,
              color: "#FFFFFF",
              fontWeight: "medium",
              backgroundColor: "#00000060",
              padding: 16,
              borderRadius: 8,
            },
          },
        },
        {
          index: 7,
          timeRange: "75-85s",
          duration: 10,
          description: "Visi masa depan / scale up",
          prompt:
            "Forward-looking vision, modern facility or expansion, growth trajectory, Indonesian pride, global ambition",
          camera: "Wide establishing, drone pull back",
          lighting: "Bright optimistic morning light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "crane-up",
          motionStrength: 0.4,
          seed: 40008,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Menuju {tagline}",
              position: "center",
              fontSize: 44,
              color: "#FFFFFF",
              fontWeight: "bold",
            },
          },
        },
        {
          index: 8,
          timeRange: "85-90s",
          duration: 5,
          description: "End card - logo, tagline, kontak",
          prompt:
            "Clean brand end card, logo animation, tagline, website, social handles, jingle audio sync",
          camera: "Static",
          lighting: "Brand color gradient background",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 40009,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "center", scale: 2.0 },
            text: {
              content: "{brand_name}\n{tagline}\n{website} | @{instagram}",
              position: "bottom-center",
              fontSize: 32,
              color: "#FFFFFF",
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 6: UGC/Review Authentic - 20 Detik
    // ============================================
    {
      name: "UGC/Review Authentic - 20 Detik",
      slug: "umkm-ugc-review-20s",
      description:
        "Format UGC style 20 detik yang terasa authentic, bukan iklan. Cocok untuk testimoni pelanggan, influencer mikro, review jujur. Struktur: Unboxing/First Reaction (3s) → Real Usage (7s) → Honest Talk (7s) → Casual CTA (3s).",
      category: "UMKM",
      tags: ["ugc", "review", "authentic", "testimoni", "influencer", "20s"],
      industry: "E-commerce",
      format: "REELS",
      style: "Authentic/UGC",
      totalDuration: 20,
      aspectRatio: "9:16",
      shotCount: 4,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["bottom-right"], required: false },
        colors: { required: false, minCount: 1, maxCount: 2 },
        font: { required: true, suggestions: ["Inter", "DM Sans", "Nunito"] },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 25,
          },
          {
            key: "rating",
            label: "Rating (1-5)",
            required: true,
            maxLength: 3,
          },
          {
            key: "key_benefit",
            label: "Manfaat Utama",
            required: true,
            maxLength: 40,
          },
          {
            key: "customer_name",
            label: "Nama Customer",
            required: false,
            maxLength: 20,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Cek di Bio",
          },
        ],
      },
      creditsCost: 4,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Hook - unboxing / first reaction",
          prompt:
            "Authentic unboxing moment, genuine surprise/excitement, phone camera POV, raw lighting, Indonesian home setting",
          camera: "Phone POV, wide selfie angle",
          lighting: "Room light, natural",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "handheld",
          motionStrength: 0.6,
          seed: 50001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Pesan {product_name} 📦",
              position: "top-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 8,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-10s",
          duration: 7,
          description: "Penggunaan real - close up texture/detail",
          prompt:
            "Close up product texture/application, real usage, honest demonstration, imperfections welcome, relatable",
          camera: "Phone close-up, shaky",
          lighting: "Available light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "handheld",
          motionStrength: 0.5,
          seed: 50002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "⭐⭐⭐⭐⭐ {rating}/5",
              position: "top-right",
              fontSize: 28,
              color: "#FFD700",
            },
          },
        },
        {
          index: 2,
          timeRange: "10-17s",
          duration: 7,
          description: "Testimoni jujur - talking to camera",
          prompt:
            "Person talking to camera naturally, Indonesian colloquial, genuine review, not scripted feeling, subtle gestures",
          camera: "Selfie mode, eye level",
          lighting: "Ring light or window",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 50003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: '"{key_benefit}"',
              position: "bottom-center",
              fontSize: 32,
              color: "#FFFFFF",
              backgroundColor: "#1A202CCC",
              padding: 12,
              borderRadius: 12,
            },
          },
        },
        {
          index: 3,
          timeRange: "17-20s",
          duration: 3,
          description: "CTA casual - link bio / kode",
          prompt:
            "Casual sign off, pointing to caption/bio, friendly wave, authentic ending",
          camera: "Selfie, pulled back",
          lighting: "Same as before",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 50004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{customer_name} | {cta} 👇",
              position: "bottom-center",
              fontSize: 30,
              color: "#FFFFFF",
              backgroundColor: "#2D3748",
              padding: 10,
              borderRadius: 8,
            },
          },
        },
      ],
    },
  ];

  for (const template of indonesianTemplates) {
    const existing = await prisma.storyboardTemplate.findUnique({
      where: { slug: template.slug },
    });

    if (existing) {
      console.log(`⏭️  Skipping existing template: ${template.slug}`);
      continue;
    }

    await prisma.storyboardTemplate.create({
      data: {
        name: template.name,
        slug: template.slug,
        description: template.description,
        category: template.category,
        tags: template.tags,
        industry: template.industry,
        format: template.format,
        style: template.style,
        totalDuration: template.totalDuration,
        aspectRatio: template.aspectRatio,
        shotCount: template.shotCount,
        referenceStyleUrl: template.referenceStyleUrl,
        referenceStyleType: template.referenceStyleType,
        brandKitSlots: template.brandKitSlots,
        creditsCost: template.creditsCost,
        isPublished: template.isPublished,
        isOfficial: template.isOfficial,
        shots: {
          create: template.shots.map((shot) => ({
            index: shot.index,
            timeRange: shot.timeRange,
            duration: shot.duration,
            description: shot.description,
            prompt: shot.prompt,
            negativePrompt: shot.negativePrompt,
            camera: shot.camera,
            lighting: shot.lighting,
            generationType: shot.generationType,
            resolution: shot.resolution,
            fps: shot.fps,
            cameraMotion: shot.cameraMotion,
            motionStrength: shot.motionStrength,
            seed: shot.seed,
            referenceImageUrl: shot.referenceImageUrl,
            referenceRole: shot.referenceRole,
            referenceWeight: shot.referenceWeight,
            brandKitOverlays: shot.brandKitOverlays,
            previewUrl: null,
            previewGeneratedAt: null,
          })),
        },
      },
    });

    console.log(
      `✅ Created template: ${template.name} (${template.shotCount} shots, ${template.totalDuration}s)`,
    );
  }

  console.log("🎉 Seeding completed!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
