import { PrismaClient } from "@prisma/client";

declare const process: { exit(code?: number): void };

const prisma = new PrismaClient();

async function main() {
  console.log(
    "🌱 Seeding Indonesian UMKM templates (Consolidated - 10 templates)...",
  );

  // Indonesian UMKM Templates - Consolidated
  // Phase 1: 6 templates existing (updated metadata from SQL)
  // Phase 2: 4 templates baru dari SQL (hero-skincare, flash-sale-tiktok, founder-story, ramadhan-promo)
  const indonesianTemplates = [
    // ============================================
    // TEMPLATE 1: Showcase Produk UMKM - 30 Detik
    // ============================================
    {
      name: "Showcase Produk UMKM - 30 Detik",
      slug: "umkm-produk-showcase-30s",
      description:
        "Template showcase produk UMKM klasik 30 detik untuk Instagram Reels/TikTok. Cocok untuk makanan, fashion, skincare, dan aksesoris. Struktur: Hook (3s) → Product Demo (12s) → Benefit (10s) → CTA (5s).",
      category: "UMKM",
      tags: ["produk", "showcase", "reels", "tiktok", "30s", "indonesia"],
      industry: "E-commerce",
      format: "REELS",
      style: "Commercial",
      totalDuration: 30,
      aspectRatio: "9:16",
      shotCount: 5,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "Poppins", "Montserrat"],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 30,
          },
          {
            key: "price",
            label: "Harga",
            required: false,
            defaultValue: "Mulai Rp 49.000",
          },
          { key: "promo", label: "Kode Promo", required: false },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Beli Sekarang",
          },
        ],
      },
      creditsCost: 5,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Hook visual - close up produk",
          prompt:
            "Ultra close-up premium product shot, dramatic rim lighting, cinematic color grading",
          negativePrompt: "blur, low quality",
          camera: "Macro 100mm",
          lighting: "Dramatic rim light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 10001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 1,
          timeRange: "3-15s",
          duration: 12,
          description: "Product demo dengan slow motion",
          prompt:
            "Product in use demonstration, slow motion 60fps, Indonesian home setting",
          negativePrompt: "staged, fake",
          camera: "Handheld 35mm",
          lighting: "Natural window light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "handheld",
          motionStrength: 0.4,
          seed: 10002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: { logo: { position: "bottom-right" } },
        },
        {
          index: 2,
          timeRange: "15-25s",
          duration: 10,
          description: "Benefit highlights",
          prompt: "Clean benefit showcase, key features highlighted",
          negativePrompt: "cluttered, dark",
          camera: "Static medium 50mm",
          lighting: "Bright even lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 10003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{feature_1}\\n{feature_2}\\n{feature_3}",
              position: "bottom-center",
              fontSize: 28,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 3,
          timeRange: "25-28s",
          duration: 3,
          description: "Social proof - rating",
          prompt: "Quick testimonial flash, 5-star rating animation",
          negativePrompt: "fake, acted",
          camera: "Selfie style",
          lighting: "Ring light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 10004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "⭐⭐⭐⭐⭐ {rating}/5",
              position: "center",
              fontSize: 36,
              color: "#FFD700",
            },
          },
        },
        {
          index: 4,
          timeRange: "28-30s",
          duration: 2,
          description: "CTA akhir",
          prompt: "Clean end card, product packshot, promo code",
          negativePrompt: "cluttered, cheap",
          camera: "Static centered",
          lighting: "Even studio lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 10005,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-center", scale: 1.2 },
            text: {
              content: "{product_name}\\n{price}\\nKode: {promo}\\n{cta}",
              position: "center",
              fontSize: 32,
              color: "#FFFFFF",
              backgroundColor: "#1A1A2E",
              padding: 20,
              borderRadius: 16,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 2: Problem-Solution Story - 20 Detik
    // ============================================
    {
      name: "Problem-Solution Story - 20 Detik",
      slug: "umkm-problem-solution-20s",
      description:
        "Format storytelling problem-solution 20 detik. Cocok untuk produk yang memecahkan masalah spesifik. Struktur: Problem (3s) → Solution (4s) → Demo (6s) → Result (4s) → CTA (3s).",
      category: "UMKM",
      tags: [
        "storytelling",
        "problem-solution",
        "skincare",
        "household",
        "20s",
      ],
      industry: "E-commerce",
      format: "REELS",
      style: "Storytelling",
      totalDuration: 20,
      aspectRatio: "9:16",
      shotCount: 5,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["top-right", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "DM Sans", "Space Grotesk"],
        },
        jingle: { required: false },
        textPlaceholders: [
          { key: "problem", label: "Masalah", required: true, maxLength: 35 },
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 25,
          },
          { key: "feature_1", label: "Fitur 1", required: true, maxLength: 30 },
          { key: "feature_2", label: "Fitur 2", required: true, maxLength: 30 },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Cek Produk",
          },
        ],
      },
      creditsCost: 4,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Problem - relatable pain point",
          prompt:
            "Clean modern problem visualization, person struggling with {problem}, muted colors",
          negativePrompt: "dramatic, messy",
          camera: "Static wide 35mm",
          lighting: "Cool flat lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 100001,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{problem}? 🤔",
              position: "center",
              fontSize: 36,
              color: "#EF4444",
              fontWeight: "medium",
              backgroundColor: "#FEF2F2",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-7s",
          duration: 4,
          description: "Solution reveal",
          prompt: "Clean product reveal, lighting shifts to warm/bright",
          negativePrompt: "chaotic, dark",
          camera: "Medium 50mm",
          lighting: "Bright warm key light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-zoom-in",
          motionStrength: 0.3,
          seed: 100002,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-right" },
            text: {
              content: "Solusi: {product_name}",
              position: "bottom-center",
              fontSize: 32,
              color: "#22C55E",
            },
          },
        },
        {
          index: 2,
          timeRange: "7-13s",
          duration: 6,
          description: "Demo cepat - fitur utama",
          prompt: "Quick feature montage, {feature_1}, {feature_2}",
          negativePrompt: "slow, confusing",
          camera: "Fast cuts",
          lighting: "Bright commercial",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "fast-cut",
          motionStrength: 0.7,
          seed: 100003,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "✨ {feature_1}\\n✨ {feature_2}",
              position: "bottom-center",
              fontSize: 24,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 6,
            },
          },
        },
        {
          index: 3,
          timeRange: "13-17s",
          duration: 4,
          description: "Result - problem solved",
          prompt: "Satisfied user, problem solved, genuine smile",
          negativePrompt: "fake smile, forced",
          camera: "Medium close-up 85mm",
          lighting: "Warm golden hour",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 100004,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Masalah terpecahkan! ✅",
              position: "center",
              fontSize: 36,
              color: "#22C55E",
              fontWeight: "bold",
            },
          },
        },
        {
          index: 4,
          timeRange: "17-20s",
          duration: 3,
          description: "CTA - brand + action",
          prompt: "Clean brand end frame, CTA button",
          negativePrompt: "amateur, cluttered",
          camera: "Static centered",
          lighting: "Brand gradient",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 100005,
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "center" },
            text: {
              content: "{cta}",
              position: "bottom-center",
              fontSize: 40,
              color: "#FFFFFF",
              backgroundColor: "#1A1A2E",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 3: How-To/Tutorial - 60 Detik (MERGED metadata from SQL)
    // ============================================
    {
      name: "How-To/Tutorial - 60 Detik",
      slug: "umkm-howto-tutorial-60s",
      description:
        "Format tutorial/educational 60 detik untuk produk yang butuh demonstrasi. Struktur: Hook (5s) → Intro (10s) → Step 1 (10s) → Step 2 (10s) → Step 3 (10s) → Result (10s) → CTA (5s).",
      category: "UMKM",
      // Merged tags dari TS + SQL
      tags: [
        "tutorial",
        "how-to",
        "howto",
        "educational",
        "edukasi",
        "skincare",
        "masak",
        "cooking",
        "diy",
        "60s",
        "indonesia",
      ],
      // Updated from SQL: "E-commerce" → "Education/E-commerce"
      industry: "Education/E-commerce",
      format: "REELS",
      style: "Educational",
      totalDuration: 60,
      aspectRatio: "9:16",
      shotCount: 7,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        // Updated from SQL: ["top-left"] → ["top-right", "bottom-right"]
        logo: { positions: ["top-right", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 4 },
        // Merged font suggestions
        font: {
          required: true,
          suggestions: [
            "Inter",
            "DM Sans",
            "Space Grotesk",
            "Plus Jakarta Sans",
          ],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 25,
          },
          { key: "step_1", label: "Langkah 1", required: true, maxLength: 30 },
          { key: "step_2", label: "Langkah 2", required: true, maxLength: 30 },
          { key: "step_3", label: "Langkah 3", required: true, maxLength: 30 },
          {
            key: "result",
            label: "Hasil Akhir",
            required: true,
            maxLength: 35,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Coba Sekarang",
          },
          { key: "website", label: "Website/IG", required: false },
        ],
      },
      creditsCost: 7,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-5s",
          duration: 5,
          description: "Problem hook",
          prompt: "Relatable problem scenario, Indonesian person frustrated",
          camera: "Close-up 85mm",
          lighting: "Dramatic side lighting",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 20001,
          negativePrompt: "overacted, fake",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{problem}",
              position: "center",
              fontSize: 48,
              color: "#FFFFFF",
              backgroundColor: "#E53E3E",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
        {
          index: 1,
          timeRange: "5-15s",
          duration: 10,
          description: "Introduksi produk",
          prompt: "Product reveal as solution, bright lighting",
          camera: "Medium 50mm",
          lighting: "Bright high key",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-zoom-in",
          motionStrength: 0.3,
          seed: 20002,
          negativePrompt: "dark, gloomy",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-right" },
            text: {
              content: "Solusi: {product_name}",
              position: "bottom-center",
              fontSize: 40,
              color: "#2F855A",
            },
          },
        },
        {
          index: 2,
          timeRange: "15-25s",
          duration: 10,
          description: "Step 1",
          prompt: "Clear step-by-step demonstration, hands showing action",
          camera: "Top-down 45° 35mm",
          lighting: "Bright shadowless",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.2,
          seed: 20003,
          negativePrompt: "rushed, unclear",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "1️⃣ {step_1}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#2B6CB0",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 3,
          timeRange: "25-35s",
          duration: 10,
          description: "Step 2",
          prompt: "Close up technique detail, precise movements",
          camera: "Macro 100mm",
          lighting: "Focused task light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 20004,
          negativePrompt: "shaky, blurry",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "2️⃣ {step_2}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#2B6CB0",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 4,
          timeRange: "35-45s",
          duration: 10,
          description: "Step 3",
          prompt: "Final step completion, satisfying result reveal",
          camera: "Medium wide 35mm",
          lighting: "Natural bright",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-pan",
          motionStrength: 0.2,
          seed: 20005,
          negativePrompt: "messy, incomplete",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "3️⃣ {step_3}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#2B6CB0",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 5,
          timeRange: "45-55s",
          duration: 10,
          description: "Result reveal",
          prompt: "Dramatic result reveal, before/after transformation",
          camera: "Split screen 50mm",
          lighting: "Bright confident",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 20006,
          negativePrompt: "subtle, unclear",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "✨ {result}",
              position: "center",
              fontSize: 52,
              color: "#2F855A",
              fontWeight: "bold",
            },
          },
        },
        {
          index: 6,
          timeRange: "55-60s",
          duration: 5,
          description: "CTA",
          prompt: "Clean end frame, logo, CTA button",
          camera: "Static centered",
          lighting: "Even studio",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 20007,
          negativePrompt: "cluttered",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "center", scale: 1.5 },
            text: {
              content: "{cta}\\n{website}",
              position: "bottom-center",
              fontSize: 42,
              color: "#FFFFFF",
              backgroundColor: "#1A202C",
              padding: 20,
              borderRadius: 12,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 4: Flash Sale/Promo - 15 Detik
    // ============================================
    {
      name: "Flash Sale/Promo - 15 Detik",
      slug: "umkm-flash-sale-15s",
      description:
        "Format flash sale 15 detik high energy untuk promo terbatas. Struktur: Discount Hook (3s) → Product Grid (5s) → Timer + Code (4s) → CTA (3s).",
      category: "UMKM",
      tags: ["flash-sale", "promo", "discount", "urgency", "15s", "fomo"],
      industry: "E-commerce",
      format: "REELS",
      style: "High Energy",
      totalDuration: 15,
      aspectRatio: "9:16",
      shotCount: 4,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["top-left", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "Poppins", "Montserrat", "Bebas Neue"],
        },
        jingle: {
          required: true,
          suggestions: ["Upbeat jingle", "SFX whoosh", "Countdown tick"],
        },
        textPlaceholders: [
          {
            key: "discount",
            label: "Diskon (contoh: 50%)",
            required: true,
            maxLength: 10,
          },
          {
            key: "deadline",
            label: "Batas Waktu",
            required: true,
            maxLength: 30,
          },
          {
            key: "promo_code",
            label: "Kode Promo",
            required: true,
            maxLength: 15,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Beli Sekarang",
          },
        ],
      },
      creditsCost: 4,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Hook - big discount",
          prompt:
            "Huge animated discount number bursting onto screen, energetic particles, Indonesian festival vibe",
          camera: "Static centered",
          lighting: "High contrast vibrant",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.8,
          seed: 30001,
          negativePrompt: "static, boring",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{discount} OFF!",
              position: "center",
              fontSize: 96,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#E53E3E",
              padding: 24,
              borderRadius: 16,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-8s",
          duration: 5,
          description: "Product grid cepat",
          prompt: "Fast-paced product grid montage, 3-4 products quick cuts",
          camera: "Quick cuts",
          lighting: "Bright commercial",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "fast-cut",
          motionStrength: 0.9,
          seed: 30002,
          negativePrompt: "slow, single product",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: { logo: { position: "top-left" } },
        },
        {
          index: 2,
          timeRange: "8-12s",
          duration: 4,
          description: "Timer + promo code",
          prompt:
            "Animated countdown timer, promo code prominently displayed, FOMO atmosphere",
          camera: "Static",
          lighting: "High contrast red/black",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.3,
          seed: 30003,
          negativePrompt: "calm, no urgency",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "⏰ {deadline}\\n🔥 KODE: {promo_code}",
              position: "center",
              fontSize: 40,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#C53030",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
        {
          index: 3,
          timeRange: "12-15s",
          duration: 3,
          description: "CTA final",
          prompt: "Strong final CTA, swipe up animation, brand logo",
          camera: "Static",
          lighting: "Brand colors",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.2,
          seed: 30004,
          negativePrompt: "weak CTA",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-left" },
            text: {
              content: "{cta} 👆\\nLink di Bio",
              position: "bottom-center",
              fontSize: 48,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#2D3748",
              padding: 20,
              borderRadius: 12,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 5: Brand Story/Founder - 90 Detik
    // ============================================
    {
      name: "Brand Story/Founder - 90 Detik",
      slug: "umkm-brand-story-90s",
      description:
        "Format brand story 90 detik untuk menceritakan journey founder dan koneksi emosional. Cocok untuk about us page, investor pitch. 9 shots: Origin → Founder → Flashback → Process → Sourcing → Team → Customers → Vision → End Card.",
      category: "UMKM",
      tags: [
        "brand-story",
        "founder",
        "documentary",
        "heritage",
        "90s",
        "emotional",
      ],
      industry: "E-commerce",
      format: "REELS",
      style: "Documentary",
      totalDuration: 90,
      aspectRatio: "9:16",
      shotCount: 9,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["center", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 4 },
        font: {
          required: true,
          suggestions: [
            "Inter",
            "DM Sans",
            "Space Grotesk",
            "Playfair Display",
          ],
        },
        jingle: {
          required: true,
          suggestions: [
            "Ambient brand track",
            "Traditional Indonesian",
            "Heartwarming melody",
          ],
        },
        textPlaceholders: [
          {
            key: "founder_name",
            label: "Nama Pendiri",
            required: true,
            maxLength: 30,
          },
          {
            key: "brand_name",
            label: "Nama Brand",
            required: true,
            maxLength: 25,
          },
          {
            key: "year_founded",
            label: "Tahun Berdiri",
            required: true,
            maxLength: 4,
          },
          {
            key: "mission",
            label: "Misi Brand",
            required: true,
            maxLength: 50,
          },
          { key: "tagline", label: "Tagline", required: true, maxLength: 40 },
          { key: "website", label: "Website", required: false },
          { key: "instagram", label: "Instagram Handle", required: false },
        ],
      },
      creditsCost: 9,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-10s",
          duration: 10,
          description: "Opening landscape Indonesia",
          prompt:
            "Cinematic wide shot Indonesian landscape, golden hour, establishing shot",
          camera: "Drone 24mm",
          lighting: "Golden hour",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-drone-pan",
          motionStrength: 0.3,
          seed: 40001,
          negativePrompt: "urban, modern building",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 1,
          timeRange: "10-20s",
          duration: 10,
          description: "Pendiri portrait",
          prompt: "Portrait of founder working passionately, authentic candid",
          camera: "Medium close-up 85mm",
          lighting: "Natural window",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 40002,
          negativePrompt: "corporate, stiff",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{founder_name}\\nPendiri {brand_name}",
              position: "lower-third",
              fontSize: 32,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 4,
            },
          },
        },
        {
          index: 2,
          timeRange: "20-30s",
          duration: 10,
          description: "Flashback/awal mula",
          prompt:
            "Vintage film look, old photos coming to life, humble beginnings",
          camera: "Vintage 16mm",
          lighting: "Warm tungsten",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-zoom",
          motionStrength: 0.2,
          seed: 40003,
          negativePrompt: "modern, digital",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Sejak {year_founded}",
              position: "center",
              fontSize: 48,
              color: "#F6E05E",
              fontWeight: "light",
            },
          },
        },
        {
          index: 3,
          timeRange: "30-42s",
          duration: 12,
          description: "Proses produksi",
          prompt:
            "Detailed craftsmanship, hands making product, traditional techniques",
          camera: "Macro + medium 50-100mm",
          lighting: "Directional craft",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-dolly",
          motionStrength: 0.2,
          seed: 40004,
          negativePrompt: "factory, automated",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 4,
          timeRange: "42-52s",
          duration: 10,
          description: "Bahan baku lokal",
          prompt:
            "Local ingredients sourcing, Indonesian farmers, fresh natural materials",
          camera: "Documentary handheld",
          lighting: "Natural outdoor",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "handheld",
          motionStrength: 0.3,
          seed: 40005,
          negativePrompt: "factory, imported",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "100% Bahan Lokal Indonesia",
              position: "lower-third",
              fontSize: 28,
              color: "#2F855A",
              backgroundColor: "#F0FFF4",
              padding: 8,
              borderRadius: 4,
            },
          },
        },
        {
          index: 5,
          timeRange: "52-62s",
          duration: 10,
          description: "Tim & komunitas",
          prompt:
            "Team working together, laughter, collaboration, gotong royong",
          camera: "Wide 35mm",
          lighting: "Warm inclusive",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-pan",
          motionStrength: 0.2,
          seed: 40006,
          negativePrompt: "corporate, stiff",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Tim yang Penuh Semangat",
              position: "lower-third",
              fontSize: 28,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 4,
            },
          },
        },
        {
          index: 6,
          timeRange: "62-75s",
          duration: 13,
          description: "Pelanggan/testimoni",
          prompt:
            "Happy customers using product, genuine smiles, diverse Indonesian faces",
          camera: "Candid 35-50mm",
          lighting: "Natural lifestyle",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 40007,
          negativePrompt: "staged, fake",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{mission}",
              position: "center",
              fontSize: 36,
              color: "#FFFFFF",
              fontWeight: "medium",
              backgroundColor: "#00000060",
              padding: 16,
              borderRadius: 8,
            },
          },
        },
        {
          index: 7,
          timeRange: "75-85s",
          duration: 10,
          description: "Visi masa depan",
          prompt:
            "Forward-looking vision, modern facility expansion, Indonesian pride",
          camera: "Wide drone pull back",
          lighting: "Bright optimistic",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "crane-up",
          motionStrength: 0.4,
          seed: 40008,
          negativePrompt: "small, limited",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Menuju {tagline}",
              position: "center",
              fontSize: 44,
              color: "#FFFFFF",
              fontWeight: "bold",
            },
          },
        },
        {
          index: 8,
          timeRange: "85-90s",
          duration: 5,
          description: "End card",
          prompt: "Clean brand end card, logo animation, tagline, contact",
          camera: "Static",
          lighting: "Brand gradient",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 40009,
          negativePrompt: "cluttered",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "center", scale: 2.0 },
            text: {
              content: "{brand_name}\\n{tagline}\\n{website} | @{instagram}",
              position: "bottom-center",
              fontSize: 32,
              color: "#FFFFFF",
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 6: UGC/Review - 20 Detik (MERGED tags from SQL)
    // ============================================
    {
      name: "UGC/Review Authentic - 20 Detik",
      slug: "umkm-ugc-review-20s",
      description:
        "Format UGC style 20 detik yang terasa authentic. Cocok untuk testimoni pelanggan, influencer mikro. Struktur: Unboxing (3s) → Real Usage (7s) → Honest Talk (7s) → CTA (3s).",
      category: "UMKM",
      // Merged tags dari TS + SQL
      tags: [
        "ugc",
        "review",
        "testimoni",
        "authentic",
        "influencer",
        "reels",
        "tiktok",
        "social-proof",
        "20s",
        "indonesia",
      ],
      industry: "E-commerce",
      format: "REELS",
      style: "Authentic/UGC",
      totalDuration: 20,
      aspectRatio: "9:16",
      shotCount: 4,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["bottom-right"], required: false },
        colors: { required: false, minCount: 1, maxCount: 2 },
        font: { required: true, suggestions: ["Inter", "DM Sans", "Nunito"] },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 25,
          },
          {
            key: "rating",
            label: "Rating (1-5)",
            required: true,
            maxLength: 3,
          },
          {
            key: "key_benefit",
            label: "Manfaat Utama",
            required: true,
            maxLength: 40,
          },
          {
            key: "customer_name",
            label: "Nama Customer",
            required: false,
            maxLength: 20,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Cek di Bio",
          },
        ],
      },
      creditsCost: 4,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Hook - unboxing",
          prompt:
            "Authentic unboxing moment, genuine surprise, phone camera POV, Indonesian home setting",
          camera: "Phone POV",
          lighting: "Room light natural",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "handheld",
          motionStrength: 0.6,
          seed: 50001,
          negativePrompt: "professional, studio",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Pesan {product_name} 📦",
              position: "top-center",
              fontSize: 36,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 8,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-10s",
          duration: 7,
          description: "Real usage close-up",
          prompt:
            "Close up product texture/application, real usage, imperfections welcome",
          camera: "Phone close-up shaky",
          lighting: "Available light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "handheld",
          motionStrength: 0.5,
          seed: 50002,
          negativePrompt: "perfect lighting, studio",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "⭐⭐⭐⭐⭐ {rating}/5",
              position: "top-right",
              fontSize: 28,
              color: "#FFD700",
            },
          },
        },
        {
          index: 2,
          timeRange: "10-17s",
          duration: 7,
          description: "Testimoni jujur",
          prompt:
            "Person talking to camera naturally, Indonesian colloquial, genuine review",
          camera: "Selfie eye level",
          lighting: "Ring light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 50003,
          negativePrompt: "corporate, scripted",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: '"{key_benefit}"',
              position: "bottom-center",
              fontSize: 32,
              color: "#FFFFFF",
              backgroundColor: "#1A202CCC",
              padding: 12,
              borderRadius: 12,
            },
          },
        },
        {
          index: 3,
          timeRange: "17-20s",
          duration: 3,
          description: "CTA casual",
          prompt: "Casual sign off, pointing to caption/bio, friendly wave",
          camera: "Selfie pulled back",
          lighting: "Same as before",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 50004,
          negativePrompt: "formal, branded",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{customer_name} | {cta} 👇",
              position: "bottom-center",
              fontSize: 30,
              color: "#FFFFFF",
              backgroundColor: "#2D3748",
              padding: 10,
              borderRadius: 8,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 7: Hero Skincare 15s (PORTED from SQL)
    // ============================================
    {
      name: "Hero Skincare 15s",
      slug: "hero-skincare-15s",
      description:
        "Template hero skincare 15 detik cinematic. Focus pada ingredient hero, texture close-up, glow result. Cocok untuk serum, moisturizer. Struktur: Ingredient (3s) → Texture (3s) → Application (4s) → Glow (3s) → CTA (2s).",
      category: "Product Showcase",
      tags: [
        "skincare",
        "hero",
        "ingredient",
        "glow",
        "15s",
        "reels",
        "cinematic",
      ],
      industry: "Skincare",
      format: "REELS",
      style: "Cinematic",
      totalDuration: 15,
      aspectRatio: "9:16",
      shotCount: 5,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "DM Sans", "Plus Jakarta Sans"],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "hero_ingredient",
            label: "Bahan Hero",
            required: true,
            maxLength: 25,
          },
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 30,
          },
          {
            key: "benefit",
            label: "Manfaat Utama",
            required: true,
            maxLength: 35,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Dapatkan Sekarang",
          },
        ],
      },
      creditsCost: 5,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Hero ingredient reveal",
          prompt:
            "Ultra macro cinematic shot of hero skincare ingredient, crystalline structure, prismatic light refraction, 8k detail, ethereal glow",
          camera: "Macro 100mm f/2.8",
          lighting: "Dark field microscopy, prismatic rim",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-zoom-in",
          motionStrength: 0.2,
          seed: 60001,
          negativePrompt: "blur, text, watermark",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{hero_ingredient}",
              position: "center",
              fontSize: 42,
              color: "#FFFFFF",
              fontWeight: "light",
              backgroundColor: "#00000060",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-6s",
          duration: 3,
          description: "Texture close-up",
          prompt:
            "Luxurious skincare texture visualization, silky serum dripping, cream emulsification, light catching viscosity, slow motion fluid",
          camera: "Macro 100mm 120fps",
          lighting: "Soft gradient key light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.3,
          seed: 60002,
          negativePrompt: "watery, messy",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 2,
          timeRange: "6-10s",
          duration: 4,
          description: "Application demo",
          prompt:
            "Elegant skincare application, fingertips gently pressing serum into skin, Indonesian woman, dewy healthy skin, spa-like atmosphere",
          camera: "Medium 85mm",
          lighting: "Soft ring light",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-pan",
          motionStrength: 0.15,
          seed: 60003,
          negativePrompt: "aggressive, red skin",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Apply 2-3 drops",
              position: "bottom-center",
              fontSize: 32,
              color: "#FFFFFF",
              backgroundColor: "#00000080",
              padding: 10,
              borderRadius: 8,
            },
          },
        },
        {
          index: 3,
          timeRange: "10-13s",
          duration: 3,
          description: "Glow reveal",
          prompt:
            "Radiant skin reveal, lit-from-within glow, healthy skin barrier, natural Indonesian beauty, golden hour lighting",
          camera: "Beauty 85mm",
          lighting: "Golden hour backlight",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "slow-zoom-out",
          motionStrength: 0.2,
          seed: 60004,
          negativePrompt: "oily, filtered, plastic",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "✨ {benefit}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFD700",
              fontWeight: "medium",
              backgroundColor: "#00000060",
              padding: 10,
              borderRadius: 8,
            },
          },
        },
        {
          index: 4,
          timeRange: "13-15s",
          duration: 2,
          description: "Product packshot + CTA",
          prompt:
            "Clean product hero shot, {product_name} bottle on marble, soft shadow, premium packaging",
          camera: "Static 50mm",
          lighting: "Clean studio gradient",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 60005,
          negativePrompt: "clutter, busy background",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-right", opacity: 0.9, scale: 1.0 },
            text: {
              content: "{product_name}\\n{cta}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              fontWeight: "medium",
              backgroundColor: "#1A202C",
              padding: 14,
              borderRadius: 10,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 8: Flash Sale TikTok 10s (PORTED from SQL)
    // ============================================
    {
      name: "Flash Sale TikTok 10s",
      slug: "flash-sale-tiktok-10s",
      description:
        "Template flash sale TikTok 10 detik viral, high energy. Urgensi ekstrem, jump cuts cepat. Cocok untuk F&B & Fashion. Struktur: Hook diskon (2s) → Product flash (4s) → Timer + Code (2s) → CTA (2s).",
      category: "Social Commerce",
      tags: [
        "flash-sale",
        "tiktok",
        "viral",
        "urgency",
        "10s",
        "fashion",
        "fnb",
        "ugc",
      ],
      industry: "F&B/Fashion",
      format: "TIKTOK",
      style: "UGC/Viral",
      totalDuration: 10,
      aspectRatio: "9:16",
      shotCount: 4,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["top-left"], required: false },
        colors: { required: true, minCount: 2, maxCount: 3 },
        font: {
          required: true,
          suggestions: ["Inter", "Poppins", "Montserrat", "Bebas Neue"],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "discount",
            label: "Diskon %",
            required: true,
            defaultValue: "70%",
          },
          {
            key: "promo_code",
            label: "Kode Promo",
            required: true,
            defaultValue: "VIRAL70",
          },
          {
            key: "deadline",
            label: "Batas Waktu",
            required: true,
            defaultValue: "2 Jam Lagi",
          },
          {
            key: "cta",
            label: "CTA",
            required: true,
            defaultValue: "Beli Sekarang!",
          },
        ],
      },
      creditsCost: 3,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-2s",
          duration: 2,
          description: "Hook - discount explosion",
          prompt:
            "TikTok style discount explosion, giant '70%' bouncing onto screen, glitch effects, particle burst, phone screen aesthetic, Gen Z vibe",
          camera: "Phone selfie chaotic",
          lighting: "Ring light, saturated TikTok filter",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 1.0,
          seed: 70001,
          negativePrompt: "static, boring, corporate",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{discount} OFF!! 🔥",
              position: "center",
              fontSize: 80,
              color: "#FF006E",
              fontWeight: "bold",
              backgroundColor: "#000000",
              padding: 20,
              borderRadius: 20,
            },
          },
        },
        {
          index: 1,
          timeRange: "2-6s",
          duration: 4,
          description: "Product flash - quick cuts",
          prompt:
            "Rapid fire product montage, 0.5s per product, jump cuts, trending transitions, mixed F&B and fashion, UGC style phone footage",
          camera: "Phone camera whip pans",
          lighting: "Mixed chaotic",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "fast-cut",
          motionStrength: 0.95,
          seed: 70002,
          negativePrompt: "slow, cinematic, staged",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 2,
          timeRange: "6-8s",
          duration: 2,
          description: "Timer + promo code flashing",
          prompt:
            "Urgent countdown timer 02:00:00 → 00:00:00, promo code flashing neon, screen shake, TikTok red alert aesthetic",
          camera: "Static phone screen",
          lighting: "High contrast red/black strobe",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.5,
          seed: 70003,
          negativePrompt: "calm, subtle",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "⏰ {deadline}\\n💥 CODE: {promo_code}",
              position: "center",
              fontSize: 36,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#FF006E",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
        {
          index: 3,
          timeRange: "8-10s",
          duration: 2,
          description: "CTA - point to bio",
          prompt:
            "Creator pointing down to caption/bio, excited expression, 'Link di bio!' animation, shop now button pop, chaotic genuine energy",
          camera: "Selfie close expressive",
          lighting: "Ring light saturated",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 30,
          cameraMotion: "static",
          motionStrength: 0.3,
          seed: 70004,
          negativePrompt: "polished, professional, corporate",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "{cta} 👇\\nLink di Bio!",
              position: "bottom-center",
              fontSize: 42,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#000000",
              padding: 16,
              borderRadius: 16,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 9: Founder Story 30s (PORTED from SQL)
    // ============================================
    {
      name: "Founder Story 30s",
      slug: "founder-story-30s",
      description:
        "Template founder story 30 detik documentary style. Cerita pendiri impactful: motivation → struggle → breakthrough → vision. Cocok untuk semua industry. 7 shots: Why (5s) → Struggle 1 (5s) → Struggle 2 (3s) → Breakthrough (5s) → Action (5s) → Vision (4s) → End Card (3s).",
      category: "Brand Story",
      tags: [
        "founder",
        "story",
        "documentary",
        "inspiration",
        "30s",
        "reels",
        "branding",
      ],
      industry: "All",
      format: "REELS",
      style: "Documentary",
      totalDuration: 30,
      aspectRatio: "9:16",
      shotCount: 7,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 4 },
        font: {
          required: true,
          suggestions: [
            "Merriweather",
            "Playfair Display",
            "Lora",
            "Crimson Text",
          ],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "founder_name",
            label: "Nama Pendiri",
            required: true,
            maxLength: 25,
          },
          {
            key: "brand_name",
            label: "Nama Brand",
            required: true,
            maxLength: 30,
          },
          {
            key: "why",
            label: "Mengapa Memulai",
            required: true,
            maxLength: 50,
          },
          {
            key: "struggle",
            label: "Tantangan Terbesar",
            required: true,
            maxLength: 50,
          },
          { key: "vision", label: "Visi", required: true, maxLength: 50 },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Kenal Lebih Dekat",
          },
        ],
      },
      creditsCost: 5,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-5s",
          duration: 5,
          description: "Why - motivasi memulai",
          prompt:
            "Intimate documentary interview, founder sitting in workspace, warm lighting, direct to camera, thoughtful expression, shallow depth of field",
          camera: "85mm eye level interview",
          lighting: "Natural window Rembrandt",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0.05,
          seed: 80001,
          negativePrompt: "scripted, stiff, corporate",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: '"{why}"',
              position: "bottom-center",
              fontSize: 32,
              color: "#FFFFFF",
              fontWeight: "light",
              fontStyle: "italic",
              backgroundColor: "#00000080",
              padding: 14,
              borderRadius: 8,
            },
          },
        },
        {
          index: 1,
          timeRange: "5-10s",
          duration: 5,
          description: "Struggle 1 - late night",
          prompt:
            "Late night founder grind, laptop glow on face, messy desk, coffee cups, tired but determined, moody cinematic",
          camera: "Wide 24mm low angle",
          lighting: "Single monitor cool blue",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-dolly",
          motionStrength: 0.1,
          seed: 80002,
          negativePrompt: "glamorous, team, luxury",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Struggle: {struggle}",
              position: "top-center",
              fontSize: 28,
              color: "#F6E05E",
              backgroundColor: "#00000080",
              padding: 8,
              borderRadius: 6,
            },
          },
        },
        {
          index: 2,
          timeRange: "10-13s",
          duration: 3,
          description: "Struggle 2 - rejection",
          prompt:
            "Montage of failed prototypes, rejection emails, crumpled papers, founder frustrated but not giving up, raw authentic struggle",
          camera: "Quick cuts handheld close-ups",
          lighting: "Harsh fluorescent",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "handheld",
          motionStrength: 0.4,
          seed: 80003,
          negativePrompt: "dramatic acting, crying",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {},
        },
        {
          index: 3,
          timeRange: "13-18s",
          duration: 5,
          description: "Breakthrough moment",
          prompt:
            "Breakthrough moment, first order notification, product in hand, genuine joy, team high-five, warm golden light, emotional payoff",
          camera: "Medium handheld candid",
          lighting: "Warm golden hour",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 80004,
          negativePrompt: "fake celebration, champagne",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "First breakthrough ✨",
              position: "bottom-center",
              fontSize: 32,
              color: "#2F855A",
              fontWeight: "bold",
              backgroundColor: "#F0FFF4",
              padding: 10,
              borderRadius: 8,
            },
          },
        },
        {
          index: 4,
          timeRange: "18-23s",
          duration: 5,
          description: "Product in action",
          prompt:
            "Real operations, packing orders, team working, happy customers, {brand_name} products in use, authentic workplace, gotong royong",
          camera: "Documentary 35mm",
          lighting: "Natural workspace",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-pan",
          motionStrength: 0.15,
          seed: 80005,
          negativePrompt: "staged, corporate, sterile",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "bottom-right", opacity: 0.8, scale: 0.8 },
          },
        },
        {
          index: 5,
          timeRange: "23-27s",
          duration: 4,
          description: "Vision - masa depan",
          prompt:
            "Founder looking out window/horizon, visionary gaze, modern skyline, hopeful ambitious, Indonesian dream",
          camera: "Wide back view silhouette",
          lighting: "Morning light optimistic",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-zoom-out",
          motionStrength: 0.1,
          seed: 80006,
          negativePrompt: "vague, small thinking",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: '"{vision}"',
              position: "center",
              fontSize: 30,
              color: "#FFFFFF",
              fontWeight: "medium",
              fontStyle: "italic",
              backgroundColor: "#00000060",
              padding: 14,
              borderRadius: 8,
            },
          },
        },
        {
          index: 6,
          timeRange: "27-30s",
          duration: 3,
          description: "End card - brand + CTA",
          prompt:
            "Clean brand end card, {brand_name} logo animation, tagline, documentary film aesthetic, subtle film grain",
          camera: "Static centered",
          lighting: "Dark gradient minimal",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 80007,
          negativePrompt: "salesy, cluttered",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "center", opacity: 1.0, scale: 1.5 },
            text: {
              content: "{brand_name}\\n{cta}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              fontWeight: "medium",
              backgroundColor: "#1A202C",
              padding: 16,
              borderRadius: 10,
            },
          },
        },
      ],
    },

    // ============================================
    // TEMPLATE 10: Ramadhan Promo 15s (PORTED from SQL)
    // ============================================
    {
      name: "Ramadhan Promo 15s",
      slug: "ramadhan-promo-15s",
      description:
        "Template promo Ramadhan 15 detik warm cinematic untuk Story. Nuansa spiritual, berkah, family gathering. Cocok untuk F&B & Retail. 4 shots: Opening spiritual (3s) → Product iftar (5s) → Family moment (4s) → Promo berkah (3s).",
      category: "Seasonal",
      tags: [
        "ramadhan",
        "promo",
        "iftar",
        "berkah",
        "family",
        "15s",
        "story",
        "seasonal",
      ],
      industry: "F&B/Retail",
      format: "STORY",
      style: "Warm/Cinematic",
      totalDuration: 15,
      aspectRatio: "9:16",
      shotCount: 4,
      referenceStyleUrl: null,
      referenceStyleType: null,
      brandKitSlots: {
        logo: { positions: ["top-center", "bottom-right"], required: true },
        colors: { required: true, minCount: 2, maxCount: 4 },
        font: {
          required: true,
          suggestions: ["Amiri", "Scheherazade", "Noto Nastaliq", "Poppins"],
        },
        jingle: { required: false },
        textPlaceholders: [
          {
            key: "promo_name",
            label: "Nama Promo",
            required: true,
            maxLength: 30,
          },
          { key: "discount", label: "Diskon", required: true, maxLength: 15 },
          {
            key: "product_name",
            label: "Nama Produk",
            required: true,
            maxLength: 30,
          },
          {
            key: "cta",
            label: "Call to Action",
            required: true,
            defaultValue: "Berbagi Kebahagiaan",
          },
        ],
      },
      creditsCost: 5,
      isPublished: true,
      isOfficial: true,
      shots: [
        {
          index: 0,
          timeRange: "0-3s",
          duration: 3,
          description: "Opening spiritual - moonlight",
          prompt:
            "Serene Ramadan night scene, full moon over Indonesian mosque silhouette, warm golden light, spiritual atmosphere, peaceful devotion",
          camera: "Wide 24mm looking up",
          lighting: "Warm golden moonlight",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-pan-up",
          motionStrength: 0.2,
          seed: 90001,
          negativePrompt: "daytime, crowded, modern",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Ramadan Mubarak 🌙",
              position: "center",
              fontSize: 48,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#00000060",
              padding: 16,
              borderRadius: 12,
            },
          },
        },
        {
          index: 1,
          timeRange: "3-8s",
          duration: 5,
          description: "Product iftar - buka puasa",
          prompt:
            "Elegant iftar spread presentation, dates and fruit, warm lighting, Indonesian family table setting, premium food photography",
          camera: "Overhead 45° 50mm",
          lighting: "Warm candlelight",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0.1,
          seed: 90002,
          negativePrompt: "fast food, cheap, dark",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-right" },
            text: {
              content: "{product_name}",
              position: "bottom-center",
              fontSize: 36,
              color: "#FFFFFF",
              fontWeight: "medium",
              backgroundColor: "#1A202C",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 2,
          timeRange: "8-12s",
          duration: 4,
          description: "Family moment - bahagia",
          prompt:
            "Warm family gathering moment, Indonesian family sharing iftar, genuine smiles, intergenerational joy, soft warm lighting, emotional connection",
          camera: "Medium 35mm warm",
          lighting: "Golden hour indoor",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "slow-pan",
          motionStrength: 0.15,
          seed: 90003,
          negativePrompt: "staged, sad, cold",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            text: {
              content: "Berbagi Kebahagiaan ✨",
              position: "center",
              fontSize: 32,
              color: "#FFFFFF",
              fontWeight: "medium",
              backgroundColor: "#00000060",
              padding: 12,
              borderRadius: 8,
            },
          },
        },
        {
          index: 3,
          timeRange: "12-15s",
          duration: 3,
          description: "Promo berkah",
          prompt:
            "Elegant promotional end card, Ramadan colors (gold/green/white), {promo_name} display, blessing messaging, Islamic geometric pattern",
          camera: "Static centered",
          lighting: "Warm gold gradient",
          generationType: "TEXT_TO_VIDEO",
          resolution: "1080p",
          fps: 24,
          cameraMotion: "static",
          motionStrength: 0,
          seed: 90004,
          negativePrompt: "cheap, cluttered, aggressive",
          referenceImageUrl: null,
          referenceRole: null,
          referenceWeight: null,
          brandKitOverlays: {
            logo: { position: "top-center" },
            text: {
              content: "{promo_name}\\n{discount}\\n{cta}",
              position: "center",
              fontSize: 40,
              color: "#FFFFFF",
              fontWeight: "bold",
              backgroundColor: "#1B4D3E",
              padding: 20,
              borderRadius: 12,
            },
          },
        },
      ],
    },
  ];

  // Seed each template
  for (const template of indonesianTemplates) {
    const existing = await prisma.storyboardTemplate.findUnique({
      where: { slug: template.slug },
    });

    if (existing) {
      console.log(`⏭️  Skipping existing template: ${template.slug}`);
      continue;
    }

    await prisma.storyboardTemplate.create({
      data: {
        name: template.name,
        slug: template.slug,
        description: template.description,
        category: template.category,
        tags: template.tags,
        industry: template.industry,
        format: template.format,
        style: template.style,
        totalDuration: template.totalDuration,
        aspectRatio: template.aspectRatio,
        shotCount: template.shotCount,
        referenceStyleUrl: template.referenceStyleUrl,
        referenceStyleType: template.referenceStyleType,
        brandKitSlots: template.brandKitSlots,
        creditsCost: template.creditsCost,
        isPublished: template.isPublished,
        isOfficial: template.isOfficial,
        shots: {
          create: template.shots.map((shot) => ({
            index: shot.index,
            timeRange: shot.timeRange,
            duration: shot.duration,
            description: shot.description,
            prompt: shot.prompt,
            negativePrompt: shot.negativePrompt ?? null,
            camera: shot.camera,
            lighting: shot.lighting,
            generationType: shot.generationType,
            resolution: shot.resolution,
            fps: shot.fps,
            cameraMotion: shot.cameraMotion,
            motionStrength: shot.motionStrength ?? null,
            seed: shot.seed ?? null,
            referenceImageUrl: shot.referenceImageUrl ?? null,
            referenceRole: shot.referenceRole ?? null,
            referenceWeight: shot.referenceWeight ?? null,
            brandKitOverlays: shot.brandKitOverlays ?? null,
            previewUrl: null,
            previewGeneratedAt: null,
          })),
        },
      },
    });

    console.log(
      `✅ Created template: ${template.name} (${template.shotCount} shots, ${template.totalDuration}s)`,
    );
  }

  console.log("🎉 Seeding completed! Total 10 templates.");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
